### ISSUE TITLE
output value unchanging

### ISSUE THREAD

**Issue by jedgarpark** [adafruit/Adafruit_CircuitPython_LIS3MDL#4]
running simpletest.py on Clue I'm getting `Magnetic: -27.360 38.410 27.901 uTesla` no matter what I do waving a magnet near sensor.

**Comment by ladyada** [comment]
@siddacious hmm take a look?

**Comment by ladyada** [comment]
jp, try hard-rebooting as well

**Comment by jedgarpark** [comment]
@ladyada hard reboot worked! I'm now seeing values change.

**Comment by ladyada** [comment]
ok great, the lis3mdl seems to do this sometimes. im not sure why :/

**Comment by jedgarpark** [comment]
Got it. I'll close this issue.

**Comment by kevinjwalters** [comment]
I am seeing this too on a CLUE running 5.3.1. I'm specifically trying to read it at 1000 samples per second in 1000Hz (without reading `STATUS_REG (27h)`) so in my case it feels like a race condition. I think it may recover on its own after a minute or two in my case. Using the `reset()` method does _not_ help.
